### ISSUE TITLE
Фортуна / Subaru

### ISSUE THREAD

**Issue by DanaVaskiv** [ashustov/test#11]

**Comment by Shtukin** [comment]
Дилера предупредил, как будет готова отправлять на 
Дмитрий Варич. 
d.varich@belgorod.subaru.ru
d.varich@motorlandgroup.ru
и Ольга Хан khanolga.1c@gmail.com

**Comment by DanaVaskiv** [comment]
26.06.2017 запланировали обновление и настройку после 20-00

**Comment by DanaVaskiv** [comment]
Изменения в конфу перенесла, обновить не смогла, конфа файловая, нет прав чтобы сбросить пользователей, ждем когда обновят. После обновления можно настраивать.

**Comment by DanaVaskiv** [comment]
Обновили и настроили, осталось показать, уточнить как выгружать работы и запчасти(итоговой строкой или подробно)  и можно включать регулярную выгрузку

**Comment by DanaVaskiv** [comment]
Загружены данные с начала июня, включена регулярная выгрузка
