### ISSUE TITLE
Феникс Авто Лекс / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#12]

**Comment by ashustov** [comment]
Оплачено

**Comment by DanaVaskiv** [comment]
Отправлена конф.  https://drive.google.com/file/d/0B_mMwplk8K-lTkwyRmM5eXpSbjA/view. Настройку запланировали на завтра 11-12 по Мск

**Comment by DanaVaskiv** [comment]
Проверили выгрузку в тест, показала все настройки, сегодня обновят платформу и обновят и настроят рабочую 1С

**Comment by Shtukin** [comment]
планируется переход с 8,2 на 8,3.

**Comment by Shtukin** [comment]
Дилер планирует не использовать CRM систему как в ОП так и в Сервисе. Со слов Даны.

**Comment by DanaVaskiv** [comment]
Включили выгрузку в рабочую версию.

**Comment by DanaVaskiv** [comment]
Доработать выгрузку в CRM

**Comment by Shtukin** [comment]
http://fenix.autocrm.ru
api
123api

**Comment by DanaVaskiv** [comment]
отправлено bikbulatovvr@fenix-auto.ru, m.shtukin@autocrm.ru

**Comment by Shtukin** [comment]
данные в DSF приходят, в CRM нет

**Comment by Shtukin** [comment]
Общался с Бикбулатовым. ITшник в отпуске до 11,09. Должны внедрить обработку 12

**Comment by DanaVaskiv** [comment]
Дорабатывала на конфу которая у меня была, попросили перенести на их обновленную конфу. Бикбулатов: вижу, что конфигурация на которой делали Вы 5.0.12.2, а мы как бы уже давно подтянулись до 5.1.11.05 и на 8.3 перешли...

**Comment by DanaVaskiv** [comment]
перенесла доработки, отправила https://drive.google.com/file/d/0B_mMwplk8K-lX0V6ZDM2TXhWeFk/view
