### ISSUE TITLE
Субару Центр Самара / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#13]

**Comment by Shtukin** [comment]
Пока не предоставили CF

**Comment by DanaVaskiv** [comment]
23.06.2017 предоставили cf, доработка до 15.07

**Comment by DanaVaskiv** [comment]
https://drive.google.com/open?id=0B_mMwplk8K-leVFxZ0JJUG9ac1E файл 1Cv8_scs_17072017.cf

**Comment by DanaVaskiv** [comment]
Настройка выгрузки в DSF  02/08/2017 на 12 по мск

**Comment by DanaVaskiv** [comment]
Проверили выгрузку в CRM: обращение приходит, ЗН и заявка на ремонт уходит в CRMю

**Comment by Shtukin** [comment]
сейчас я с ними буду разбираться. там вообще не понятно и Роман это не решит. Я сейчас сделаю обработку которая поможет понять что не так
там или у пользователей интернет закрыт или ещё что-то
потому что данные уходят от одного человека только

**Comment by DanaVaskiv** [comment]
Отправила обработку чтобы понять что не так

**Comment by Shtukin** [comment]
последний полученный заказ-наряд в DSF от 	16.08.2017

**Comment by Shtukin** [comment]
в CRM данные тоже не приходят

**Comment by Shtukin** [comment]
в DSF з/н приходят

**Comment by DanaVaskiv** [comment]
сегодня подключаюсь удаленно

**Comment by DanaVaskiv** [comment]
Нужно обновить процедуру "ПриЗаписи", в ней нет кода для передачи данных в CRM

**Comment by Shtukin** [comment]
не дообновляли 1С-ку. Именно чтобы передавались документы в CRM этого нет. Если проверять обработкой то всё выполняется, а при записи документа нет кода который должен это выполнять. Роман должен связать с программистом для внедрения.

**Comment by Shtukin** [comment]
Проверили синхру с CRM, есть замечания.
Нет рекомендаций в CRM хотя в з/н они присутствуют 
И статусы у всех з/н "закрыт"

**Comment by DanaVaskiv** [comment]
в некоторых ЗН есть рекомендации http://shot.qip.ru/00QqXp-495nqPrFf/

**Comment by Shtukin** [comment]
запланировали обучение
