### ISSUE TITLE
Планета Авто Субару / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#14]

**Comment by Shtukin** [comment]
оплата произведена

**Comment by DanaVaskiv** [comment]
Отправлена конф. https://drive.google.com/file/d/0B_mMwplk8K-lX0ZjeWk5T3R5LUk/view

**Comment by Shtukin** [comment]
сказали что внедрят 18,07

**Comment by DanaVaskiv** [comment]
Проверили передачу данных. Артём Шарипов <asharipov@planeta-avto.ru>: Сегодня ещё потестируем выгрузку и сделаем её периодической.

**Comment by DanaVaskiv** [comment]
Запустили регулярную выгрузку
