### ISSUE TITLE
Автобан / Ford

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#15]
Конфигурация лежит по ссылке https://drive.google.com/open?id=0B_OCtt2dbr_YRU8zLUJNU0t1Vk0
Оплаты пока нет, я скажу когда приступать.

**Comment by Shtukin** [comment]
пока нет оплаты, не приступать! Я скажу когда делать.

**Comment by Shtukin** [comment]
оплатили

**Comment by DanaVaskiv** [comment]
d.v.dudnikov@avtoban.biz,  k.a.tkachev@avtoban.biz, Максим Штукин(Auto CRM) <m.shtukin@autocrm.ru> отправлено 28072017.
Доработанная конфигурация по ссылке: https://drive.google.com/file/d/0B_mMwplk8K-lenZOUEhBWV9YY2M/view

Файл называется: 1Cv8_avtoban_28072017.cf

**Comment by DanaVaskiv** [comment]
отправила обработку для проверки.
