### ISSUE TITLE
Плеяды / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#16]
Нужно переделать обработку для передачи заказ-нарядов в DSF

**Comment by Shtukin** [comment]
я их предупредил.

**Comment by DanaVaskiv** [comment]
26.06.2017. Отправлена конф.

**Comment by DanaVaskiv** [comment]
27.06.2017 исправления https://drive.google.com/file/d/0B_mMwplk8K-lWlBRTlItZGRrbG8/view

**Comment by DanaVaskiv** [comment]
Написала Андрею, попросила удаленку

**Comment by DanaVaskiv** [comment]
настроили удаленный доступ, завтра утром приступаю к настройке выгрузки

**Comment by DanaVaskiv** [comment]
отладили выгрузку на тест

**Comment by DanaVaskiv** [comment]
выгрузили данные за август в рабочую, включили регулярную выгрузку

**Comment by Shtukin** [comment]
з\н в dsf выгружаются
