### ISSUE TITLE
Территория А / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#17]
Клиент в курсе что к обработке приступим только в середине Июля

**Comment by DanaVaskiv** [comment]
vladislav.shabelnik@bmw-angara.ru, Максим Штукин(Auto CRM) <m.shtukin@autocrm.ru>, Михаил Ларин(Auto CRM) <m.larin@autocrm.ru>,k.miklashevskiy@autocrm.ru <k.miklashevskiy@autocrm.ru> Отправлена конфигурация

доработанная конфигурация по ссылке :
https://drive.google.com/file/d/0B_mMwplk8K-lQzV3NDZYX3V2eDg/view
файл:
1Cv8_territory_26072017.cf

**Comment by Shtukin** [comment]
Жигарь должен связаться с Владиславом, напомнил ему по поводу настроек.

**Comment by DanaVaskiv** [comment]
Настройка запланирована на понедельник 07.08.2017

**Comment by DanaVaskiv** [comment]
Прогрузила данные в DSF. Завтра проверка выгрузки в CRM

**Comment by ashustov** [comment]
Иркутск не выгружает.

**Comment by DanaVaskiv** [comment]
в DSF данные выгружены с 01.08. Сегодня включим регулярную выгрузку. Проверка выгрузки в CRM сегодня после 16-00

**Comment by DanaVaskiv** [comment]
Проверила получение обращения из CRM, отправку ЗН в CRM. Включила выгрузку данных и в DSF и в CRM

**Comment by Shtukin** [comment]
Шабельник в отпуске до 26,08, клиентскую базу так и дали, Жигарь должен решить этот вопрос.Запланировали проверку 14,08

**Comment by Shtukin** [comment]
проблема в клиентской базе, много не корректных номеров Жигарь обещал найти ресурсы для приведения её в порядок. @DanaVaskiv В CRM получаем краткое наименование клиента а нужно полное http://shot.qip.ru/00Lsi6-44Pigc8fu/

**Comment by DanaVaskiv** [comment]
Сегодня после 16-00 по мск откорректирую

**Comment by Shtukin** [comment]
проблема с передачей обращения из CRM в 1С, подтянулся клиент с другим номером телефона. В CRM http://shot.qip.ru/00UNJc-4EBATVnMa/ в 1С http://shot.qip.ru/00UNJc-2EBATVnMb/

**Comment by DanaVaskiv** [comment]
попросила удаленный доступ у Владислава, т.к. у себя не могу воспроизвести

**Comment by DanaVaskiv** [comment]
Поправила
