### ISSUE TITLE
Мартен / Mitsubishi

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#20]
https://cloud.mail.ru/public/3g78/gY8mEDhC7
фаил предоставил Поросков Павел Геннадьевич <pgporoskov@marten.ru>
Оплачено, можно делать

**Comment by Shtukin** [comment]
http://marten-mitsubishi.autocrm.ru
API 	
aoi321
747uaa

**Comment by DanaVaskiv** [comment]
Среди измененных объектов Обработка.ЗаписьНаРемонтИОбслуживание.
У нас она не используется.
Вместо нее используется Обработка.ЖурналЗаписиНаСервис.ФормаЗаписи1 (в ней процедура ОсновныеДействияФормыСоздатьЗаявку() создает документ ЗаявкаНаРемонт).

**Comment by DanaVaskiv** [comment]
Отправила изменения pgporoskov@marten.ru, m.shtukin@autocrm.ru

**Comment by Shtukin** [comment]
связка работает корректно
