### ISSUE TITLE
Фастар / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#21]
https://cloud.mail.ru/public/Br55/mronkCh2B
Пароль к архиву 135Fastar246
Оплаты пока нет

**Comment by Shtukin** [comment]
оплачена

**Comment by DanaVaskiv** [comment]
dotsenkoaa@mazda-fastar.ru, adushkinvb@mazda-fastar.ru Василий Адушкин
доработанная конфигурация по ссылке :
https://drive.google.com/file/d/0B_mMwplk8K-lRUtQNXJDMENGX0E/view

файл:1Cv8_fastar_02082017.rar 
 
Пароль к архиву 135Fastar246

**Comment by Shtukin** [comment]
У Василия проблемы, обещал внедрить 10,08

**Comment by DanaVaskiv** [comment]
приступили к настройке

**Comment by DanaVaskiv** [comment]
Начали выгрузку в DSF

**Comment by Shtukin** [comment]
а в CRM ?

**Comment by DanaVaskiv** [comment]
в CRM ещё не включили. настраивали пока DSF, напишу им сегодня чтобы включили выгрузку в CRM

**Comment by DanaVaskiv** [comment]
отлаживаем с Василием выгрузку в CRM

**Comment by Shtukin** [comment]
Вася работает сегодня последний день. должен посмотреть почему перестала работать выгрузка в crm и dsf

**Comment by Shtukin** [comment]
Вася перед уходом всё поправил. Выгрузка в DSF и CRM идёт!

**Comment by Shtukin** [comment]
не работает выгрузка в dsf и crm. Галина должна дать контакты программиста

**Comment by DanaVaskiv** [comment]
может они могут дать удаленный доступ?

**Comment by DanaVaskiv** [comment]
данные выгружаются и в DSF и в CRM
