### ISSUE TITLE
Чешские автомобили / Skoda

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#22]

**Comment by Shtukin** [comment]
Оплатили конфигурацию

**Comment by DanaVaskiv** [comment]
до 10.08

**Comment by Shtukin** [comment]
http://cze-auto.autocrm.ru
http://shot.qip.ru/00Lsi6-44Pigc8fx/

**Comment by Shtukin** [comment]
конфигурацию высылать Александру на alexandr.suslov@cze-auto.ru

**Comment by DanaVaskiv** [comment]
Отправлено на alexandr.suslov@cze-auto.ru, m.shtukin@autocrm.ru. 
Доработанная конфигурация по ссылке:
https://drive.google.com/file/d/0B_mMwplk8K-lWElJeXVDaWUzSmc/view
файл:1Cv8_cze-auto_17082017.cf

**Comment by Shtukin** [comment]
В CRM данные не получаем из 1С.

**Comment by Shtukin** [comment]
говорят что внедрили, но данные не получаем. 
скайп поставить проблема но должны переговорить, есть тимвивер. Александр 8-951-083-94-43 занимался внедрением обработки .

**Comment by Shtukin** [comment]
live:fcc20a87deb01ce6 скайп Александра.

**Comment by DanaVaskiv** [comment]
данные в CRM выгружаются

**Comment by Shtukin** [comment]
при передачи обращения из CRM возникает ошибка http://shot.qip.ru/00Lsi6-24Pigc8lO/, заполняется только ФИО

**Comment by DanaVaskiv** [comment]
Ошибку поправили 06.09.2017
