### ISSUE TITLE
М-Сервис Ростов/Subaru

### ISSUE THREAD

**Issue by DanaVaskiv** [ashustov/test#24]

**Comment by DanaVaskiv** [comment]
до 16.08

**Comment by DanaVaskiv** [comment]
доработанная конфигурация по ссылке https://drive.google.com/file/d/0B_mMwplk8K-ldWQ0UmxGNllZVjg/view
файл:1Cv8_mservice_15082017.cf
Отправлено: n_sikorskaya@subaru-rostov.ru, m.larin@autocrm.ru, m.shtukin@autocrm.ru, maltsev.sergey@subaru-motor.ru, k.miklashevskiy@autocrm.ru

**Comment by DanaVaskiv** [comment]
Приступили к настройке

**Comment by DanaVaskiv** [comment]
отладила всё в тестовой базе, можно переносить в рабочую. На старом сервере не выполнялись запросы из корявого IE.

**Comment by DanaVaskiv** [comment]
Отправила вопросы Сикорской: Вопрос по выгрузке работ и запчастей ЗН: 
выгружать данные по работам и запчастям итоговой строкой либо подробно как и есть в документе?
ещё вопрос: чтобы в систему DSF корректно выгружалась информация по видам ремонта мне нужно четко понимать какой вид ремонта из 1С соответствует виду ремонта DSF.

**Comment by DanaVaskiv** [comment]
выгрузили данные за август в рабочую

**Comment by DanaVaskiv** [comment]
включила регулярную выгрузку

**Comment by Shtukin** [comment]
проверил
