### ISSUE TITLE
Кузовной ремонт

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#25]
Для Техно Авто / ЦКР нужно сделать связку с 1С. Конфигурация будет предоставлена чуть позже.
Нужно передавать из CRM в 1С данные по аналогии как с сервисом при использовании  записи в CRM. Дополнительно нужно связать "состояния" в 1С и  "задачи" в CRM. Т.е. при смене задачи в CRM, должно поменяться состояние заказ-наряда.

**Comment by Shtukin** [comment]
https://yadi.sk/d/L-Dttyi33LQnps

**Comment by Shtukin** [comment]
Дана, нужно оценить возможность и сообщить мне

**Comment by Shtukin** [comment]
http://rosso.autocrm.ru/cp/
api
api123

**Comment by DanaVaskiv** [comment]
Доработанная конфигурация по ссылке:

https://drive.google.com/open?id=0B_mMwplk8K-lMzh5NHhxT2psVWs
1Cv8_rosso_14092017.cf

Описание изменений, а также информация по настройкам подключения в приложении к письму.
В данный момент реализовано получение в документ "заказ-наряд" информации о рабочем листе кузовного отдела.
Изменение состояния заказ-наряда в зависимости от этапа рабочего листа CRM ещё в процессе разработки.
