### ISSUE TITLE
Успех Авто + / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#26]
Данные по заказ-нарядам выгружены были последний раз в июне, связки DSF и 1С нет. Системный администратор в отпуске, Ноздринёв Роман (РОС) должен решить вопрос о предоставлении удалённого доступа.
У нас есть конфигурация но она от 28,02,17

**Comment by DanaVaskiv** [comment]
https://drive.google.com/file/d/0B_mMwplk8K-leUNJRURJa1gyZ2s/view
1Cv8_dsf_uspehauto_04092017.cf
Отправлено tdir@saratov-subaru.ru, m.shtukin@autocrm.ru, e.kashtanov@autocrm.ru

**Comment by DanaVaskiv** [comment]
Начали настройку

**Comment by DanaVaskiv** [comment]
Выгрузили данные за август-сентябрь. включили регулярную выгрузку

**Comment by Shtukin** [comment]
проверил

**Comment by Shtukin** [comment]
перестала работать выгрузка в DSF

**Comment by Shtukin** [comment]
последний от 06.09.2017 19:20:37

**Comment by DanaVaskiv** [comment]
поправили. Не было настройки по состоянию ЗН
