### ISSUE TITLE
Токио-Моторс / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#29]
https://yadi.sk/d/jJXO7BO13MzGFZ 
Прислал Николай Некрасов support@t-motors-city.ru 
Выставили счет на 50к.

**Comment by DanaVaskiv** [comment]
Отправлено на support@t-motors-city.ru, e.kashtanov@autocrm.ru. Конфигурация: https://drive.google.com/file/d/0B_mMwplk8K-lM01MOUhPMG40MmM/view
1Cv8_scm_25092017.cf

**Comment by DanaVaskiv** [comment]
Выгрузили данные за сентябрь, включила регулярную выгрузку. 29.09 данные приходят
