### ISSUE TITLE
ООО "Юникор", официальный дилер LADA

### ISSUE THREAD

**Issue by DanaVaskiv** [ashustov/test#31]

**Comment by Shtukin** [comment]
Запись в 1С, сделать связку с Кузовным

**Comment by DanaVaskiv** [comment]
Запись в CRM

**Comment by Shtukin** [comment]
https://yadi.sk/d/2GrVeVOz3SS4hh

**Comment by Shtukin** [comment]
на всякий случай попросили выгрузить СF

**Comment by DanaVaskiv** [comment]
Юникор оплатил доработку конфигурации, можно приступать к работе. Они будут синхронизировать 1С с нашим отделом продаж и сервисом. Запись будут вести в 1С.

**Comment by Shtukin** [comment]
Они будут еще подключать кузовню, сложно будет сделать синхру по РЛ?

**Comment by DanaVaskiv** [comment]
У Юникора запись в CRM

**Comment by DanaVaskiv** [comment]
https://drive.google.com/file/d/1KKmgm_xLfEXmOI10QJH4tyRvVkkKbEfc/view?usp=drive_web
1Cv8_Unikor_22022018.cf

**Comment by DanaVaskiv** [comment]
поправить по кузовному
