### ISSUE TITLE
Планета Авто

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#32]
Дорабатываем 1С для работы workshop automation.
На стороне дилера уже реализовано:
1. Веб сервер настроен.
2. Планшет с приложением настроен и подключен к веб серверу.

Ответственный за проект - Зорин Константин Викторович
8-922-732-3726
kzorin@planeta-avto.ru

Завтра должен быть предоставлен доступ к веб серверу и 1С. И контакты сотрудника.

Приступать только после оплаты счета!!!!!!!!

**Comment by Shtukin** [comment]
Удаленный рабочий стол сервера Workshop Automation:
адрес: gw.planeta-avto.ru:55554
логин: WA\Administrator
пароль: planeta-avto1

Удаленный рабочий стол 1С Альфа Авто 5:
адрес: gw.planeta-avto.ru:55555
логин: AIR\wa
пароль: planeta-avto1

Ответственные лица:

Направление 1С:
Шарипов Артем. Программист 1С
Email: asharipov@planeta-avto.ru
Раб. Тел. +7(351)749-09-11 доб. 3117
Моб. Тел. +79085892265


Рук-ль отдела ИТ (все прочие вопросы):
Зорин Константин Викторович
Email: kzorin@planeta-avto.ru
Раб. Тел. +7(351)749-09-11 доб. 3485
Моб. Тел. +79227323726

**Comment by Shtukin** [comment]
Оплата поступала!

**Comment by DanaVaskiv** [comment]
В целях безопасности изменили тип подключения к нашим серверам.

Добавили туннель.


VPN подключение протокол PPTP

сервер: gw.planeta-avto.ru

логин: workshopautomation

пароль: planeta-avto1

 

Удаленный рабочий стол сервера Workshop Automation:

адрес: 192.168.255.107

логин: WA\Administrator

пароль: planeta-avto1

 

Удаленный рабочий стол 1С Альфа Авто 5:

адрес: 192.168.255.93

логин: AIR\wa

пароль: planeta-avto1
