### ISSUE TITLE
УАЗ Центр Иркутск / УАЗ

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#33]
Запись в CRM!!!!!

**Comment by Shtukin** [comment]
http://centr-irk.crm.uaz.ru 
логин - api
пароль- 321

**Comment by DanaVaskiv** [comment]
pa.kullama@bgs-auto.ru
Доработанная конфигурация по ссылке
https://drive.google.com/open?id=1CpXheDT13Tl7uHYRt9t1FiHDaZci0nTt
файл: 1Cv8_centr-irk_14112017.cf

**Comment by Shtukin** [comment]
@DanaVaskiv  Проверили связку, всё корректно. Нужно добавить связку еще в предварительную заявку

**Comment by DanaVaskiv** [comment]
сегодня добавлю

**Comment by DanaVaskiv** [comment]
Отправлено pa.kullama@bgs-auto.ru
https://drive.google.com/file/d/1cm6qTkclBjxsoArZRAcnghJuo5SjICtS/view
