### ISSUE TITLE
Феникс Авто

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#36]
Настройки подключения для проекта Hyundai Workshop Automation: Феникс-Авто НМ, г. Омск

 

Сервер VPN-подключения: vpn.fenix-auto.ru (ip-адрес: 92.255.181.100)

Пользователь VPN: autocrm

Пароль: Pas4AutoDialerCRM

Тип VPN сервера: стандартный Windows автоматический (туннель точка-точка: PPTP)

Протокол: Microsoft CHAP версия 2 (MS-CHAP v2), шифрование не обязательное

Локальный DNS: 10.18.161.30

Шлюз локальной сети не использовать, но на всякий случай ip-адрес шлюза: 10.18.161.197

 

Сервер терминала RDP: srv303.corp.fenix-auto.ru (локальный ip-адрес: 10.18.161.27)

Пользователь RDP: corp\autocrm (или autocrm@corp.fenix-auto.ru)

Пароль: Pas4AutoDialerCRM

 

тестовый Сервер 1С:Предприятие 8.3 (8.3.10.2299): srv-sql.corp.fenix-auto.ru (ip-адрес: 10.18.161.33)

тестовый Сервер БД MS SQL Server 2014: srv-sql.corp.fenix-auto.ru (ip-адрес: 10.18.161.33)

тестовая база Альфа-Авто: Автосалон+Автосервис+Автозапчасти ПРОФ, редакция 5.1 (5.1.11.05): Alfa83HMTest, кластер 2541  (для базы включена  блокировка

регламентных заданий). (Srvr="Srv-SQL:2541", Ref="Alfa83HMTest")

Настройка путей до базы под  пользователем corp\AutoCRM сделана.

Пользователь тестовой базы 1С: AutoCRM, пароль: 123 (полные права)

 

Сервер Hyundai Workshop Automation (HWA): srv303.corp.fenix-auto.ru (ip-адрес: 10.18.161.27)

 

На сервере Srv303 пользователь AutoCRM локальный Администратор (чтобы была возможность изменять настройки HWA, если понадобится).

 

Тестовый сервер 1С Srv-SQL (на нем же MS SQL) слабенький... с ним работает еще один программист (в другом терминале)... Если  будет

сильный тормоз, то перевезем на другой... но в принципе должно хватать.

 

Мои контакты:

Бикбулатов Валерий (группа компаний "Феникс-Авто", г. Омск)

мобильный телефон +79136236832

e-mail: bikbulatovvr@fenix-auto.ru

Skype: bikbulatovvr

 

Контакты моего 1С-программиста:

Сошников Сергей

мобильный телефон +7 9136577217

e-mail: soshnikovsa@fenix-auto.ru

Skype: soshnikov_serg

**Comment by DanaVaskiv** [comment]
не могу подключиться к vpn

http://shot.qip.ru/00QqXp-495nqPrHf/
http://shot.qip.ru/00QqXp-295nqPrHg/
http://shot.qip.ru/00QqXp-495nqPrHh/
http://shot.qip.ru/00QqXp-695nqPrHi/
http://shot.qip.ru/00QqXp-495nqPrHj/

**Comment by DanaVaskiv** [comment]
Настроили подключение
