### ISSUE TITLE
Арена Моторс / Skoda

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#5]
Конфигурацию отправили, Барбанаков в копии.

**Comment by DanaVaskiv** [comment]
20.06.2017 отправлена конфа.
https://drive.google.com/file/d/0B_mMwplk8K-lOUt5ZmJoYVFpRDA/view
1Cv8_arena_20062017.cf

**Comment by Shtukin** [comment]
связка работает

**Comment by Shtukin** [comment]
@DanaVaskiv  заказ-наряды приходят,  обращения тоже работают. Но когда на основании обращения создана предварительная заявка, в CRM обращение автоматом не закрывается! Нужно поправить. В понедельник в 11,00 по мск запланировали финальный прогон системы т.к. во вторник нужно уже начинать обучать.
