### ISSUE TITLE
Сарет Авто / Ravon

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#6]

**Comment by Shtukin** [comment]
связка не работает

**Comment by DanaVaskiv** [comment]
Пароль для service_api изменили, отправила новый пароль

**Comment by Shtukin** [comment]
Сергеев (сис.админ) не внёс настройки подключения.

**Comment by Shtukin** [comment]
Сергеев Алексей на связи по скайпу: alex.ser77 . Проблемы при передаче нового клиента. Нужно связаться и посмотреть в чем дело! Имей в виду что у них +2 часа к московскому.

**Comment by Shtukin** [comment]
расторгли договор
