### ISSUE TITLE
Авиавто / Subaru

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#7]

**Comment by DanaVaskiv** [comment]
Проверили получение данных 20.06.2017

**Comment by DanaVaskiv** [comment]
https://drive.google.com/file/d/0B_mMwplk8K-laDlsZzhsX25GZEU/view

файл: 1Cv8_dsf_aviavto_21072017.cf

**Comment by Shtukin** [comment]
zet13@mail.ru в отпуске до 31,07

**Comment by DanaVaskiv** [comment]
Начинают настройку

**Comment by Shtukin** [comment]
Яковлев не против предоставить удаленный доступ, нужно связаться с  Митюшников Борис Владимирович
+79-226-252-226.

**Comment by DanaVaskiv** [comment]
Завтра предоставят удаленный доступ

**Comment by DanaVaskiv** [comment]
прогрузили данные в DSF c 01/08  по 22/08. Завтра включим регулярную выгрузку

**Comment by DanaVaskiv** [comment]
включили регулярную выгрузку в DSF

**Comment by Shtukin** [comment]
Проверял с Яковлевым связку с CRM, у него в 1С пропало окно в заказ-наряде куда нужно вносить номер РЛ. Показать не смог т.к. в скайпе был с другого компа.

**Comment by DanaVaskiv** [comment]
сегодня верну доработки. видимо кто-то и затер

**Comment by DanaVaskiv** [comment]
обновила 1С, проверила получение данных по существующему в 1С контрагенту и по новому: данные приходят, документ обновляется
