### ISSUE TITLE
АЦ Форпост / KIA

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#8]

**Comment by DanaVaskiv** [comment]
19.06.2017 Отправлены исправления
https://drive.google.com/file/d/0B_mMwplk8K-leXB0cER3S0sySmM/view
1Cv8_forpost_16062017.cf

**Comment by Shtukin** [comment]
нужно разобраться с обращениями новых клиентов, при передачи ID в запись ругается на
 {ОбщийМодуль.CRM_РаботаСсоединением.Модуль(3078)}: Ошибка при вызове метода контекста (Записать)
     НовДоговор.Записать();
по причине:
Не удалось записать: "Договоры взаиморасчетов"!
Если нужна оперативная связь они готовы предоставить удаленный доступ.

**Comment by Shtukin** [comment]
всё остальное работает корректно

**Comment by DanaVaskiv** [comment]
Сегодня посмотрю

**Comment by DanaVaskiv** [comment]
Отправила исправления
