### ISSUE TITLE
СТО АВТО / Geely

### ISSUE THREAD

**Issue by Shtukin** [ashustov/test#9]

**Comment by Shtukin** [comment]
Сто авто я Туркину написала, как только он ответит как будем обновлять я сразу готова обновить и настроить

**Comment by DanaVaskiv** [comment]
20.06.2017 отправлена конфа.  Отв Лашин Сергей: программист 1С установит, а мы тем временем дадим вам доступ

**Comment by DanaVaskiv** [comment]
22.06.2017 Удаленку подключили, конфу ещё не обновили

**Comment by DanaVaskiv** [comment]
Планируют обновление с понедельника 26.06.2017

**Comment by Shtukin** [comment]
@DanaVaskiv  Связка работает, обращения передаются в 1С.
Проблема только в цехах! Сейчас каждый сотрудник любого из точек видит все заказ- наряды, а нужно показывать только те которые соответствуют их цеху http://shot.qip.ru/00Lsi6-54Pigc83M/, т.е. сотрудники Мичуринского должны видеть заказ-наряды цеха Мичуринский и т.д.

**Comment by Shtukin** [comment]
В 1С карточке автомобиля есть данные по началу/окончанию гарантии http://shot.qip.ru/00Lsi6-34Pigc8bS/, а в CRM эти данные не попадают. Нужно посмотреть и связаться с live:b53898964132e99d Чернышева Наталья

**Comment by DanaVaskiv** [comment]
в алгоритме прописана выгрузка полей WarrantyStart, WarrantyEnd. Нужно проверить на стороне CRM есть ли эти поля и данные в них
